require("../node_modules/uupaa.nodemodule.js/lib/NodeModule.js");
require("../node_modules/uupaa.reflection.js/lib/Reflection.js");
require("../node_modules/uupaa.console.js/lib/Console.js");
require("../node_modules/uupaa.help.js/lib/Help.js");
require("../node_modules/uupaa.valid.js/lib/Valid.js");
require("../lib/Task.js");
require("../node_modules/uupaa.test.js/lib/Test.js");
require("../release/Task.min.js");
require("./test.js");
